name: Build and Deploy
on:
  push:
    branches:
      - docs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: contamg/contamg@docs

      - name: Build and Deploy
        uses: grasilife/github-pages-deploy-action@v1.2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: docs # The branch the action should deploy from.
          REPO: contamg/contamg.github.io@master # The branch the action should deploy to.
          FOLDER: docs/.vuepress/dist # The folder the action should deploy.
          BUILD_SCRIPT: yarn install && a yarn docs:build # The build script the action should run prior to deploying.
